FROM ghost:5.59.0 AS ghost-base

WORKDIR /var/lib/ghost
ARG storage__active
ARG GHOST_STORAGE_ADAPTER_S3_PATH
ARG GHOST_STORAGE_ADAPTER_S3_ACL
ARG GHOST_STORAGE_ADAPTER_S3_ENDPOINT
ARG GHOST_STORAGE_ADAPTER_S3_ASSET_HOST
ARG GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ENV storage__active=$
ENV GHOST_STORAGE_ADAPTER_S3_PATH=$GHOST_STORAGE_ADAPTER_S3_PATH
ENV GHOST_STORAGE_ADAPTER_S3_ACL=$GHOST_STORAGE_ADAPTER_S3_ACL
ENV GHOST_STORAGE_ADAPTER_S3_ENDPOINT=$GHOST_STORAGE_ADAPTER_S3_ENDPOINT
ENV GHOST_STORAGE_ADAPTER_S3_ASSET_HOST=$GHOST_STORAGE_ADAPTER_S3_ASSET_HOST
ENV GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE=$GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
RUN npm install --prefix /tmp/ghost-storage-adapter-s3 ghost-storage-adapter-s3 && \
    cp -r /tmp/ghost-storage-adapter-s3/node_modules/ghost-storage-adapter-s3 current/core/server/adapters/storage/s3 && \
    rm -r /tmp/ghost-storage-adapter-s3

RUN npm install ghost-storage-base && npm install aws-sdk
