FROM ghost:5.59.0

WORKDIR /var/lib/ghost
ARG storage__active
ARG GHOST_STORAGE_ADAPTER_S3_PATH
ARG GHOST_STORAGE_ADAPTER_S3_ACL
ARG GHOST_STORAGE_ADAPTER_S3_ENDPOINT
ARG GHOST_STORAGE_ADAPTER_S3_ASSET_HOST
ARG GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE
ENV storage__active=$
ENV GHOST_STORAGE_ADAPTER_S3_PATH=$GHOST_STORAGE_ADAPTER_S3_PATH
ENV GHOST_STORAGE_ADAPTER_S3_ACL=$GHOST_STORAGE_ADAPTER_S3_ACL
ENV GHOST_STORAGE_ADAPTER_S3_ENDPOINT=$GHOST_STORAGE_ADAPTER_S3_ENDPOINT
ENV GHOST_STORAGE_ADAPTER_S3_ASSET_HOST=$GHOST_STORAGE_ADAPTER_S3_ASSET_HOST
ENV GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE=$GHOST_STORAGE_ADAPTER_S3_FORCE_PATH_STYLE

RUN npm install -g ghost-storage-adapter-s3 && \
    ln -s /usr/local/lib/node_modules/ghost-storage-adapter-s3 ./current/core/server/adapters/storage/s3
